# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QWidget, QApplication

import sys

import pics

class Ui_Form(QWidget):

    def __init__(self):
        QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 484)
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("Logo-4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 160))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 160))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.downl_favor_btn = QtWidgets.QPushButton(self.groupBox)
        self.downl_favor_btn.setGeometry(QtCore.QRect(0, 13, 151, 23))
        self.downl_favor_btn.setObjectName("downl_favor_btn")
        self.download_enter_btn = QtWidgets.QPushButton(self.groupBox)
        self.download_enter_btn.setGeometry(QtCore.QRect(0, 43, 151, 50))
        self.download_enter_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.download_enter_btn.setObjectName("download_enter_btn")
        self.downl_best_btn = QtWidgets.QPushButton(self.groupBox)
        self.downl_best_btn.setGeometry(QtCore.QRect(0, 101, 151, 23))
        self.downl_best_btn.setObjectName("downl_best_btn")
        self.upate_base_btn = QtWidgets.QPushButton(self.groupBox)
        self.upate_base_btn.setGeometry(QtCore.QRect(150, 101, 151, 23))
        self.upate_base_btn.setObjectName("upate_base_btn")
        self.fotorate_folder_btn = QtWidgets.QPushButton(self.groupBox)
        self.fotorate_folder_btn.setGeometry(QtCore.QRect(150, 13, 151, 23))
        self.fotorate_folder_btn.setObjectName("fotorate_folder_btn")
        self.copy_folder_chkbx = QtWidgets.QCheckBox(self.groupBox)
        self.copy_folder_chkbx.setGeometry(QtCore.QRect(189, 130, 81, 20))
        self.copy_folder_chkbx.setChecked(True)
        self.copy_folder_chkbx.setObjectName("copy_folder_chkbx")
        self.timer_chkbx = QtWidgets.QCheckBox(self.groupBox)
        self.timer_chkbx.setGeometry(QtCore.QRect(10, 130, 70, 20))
        self.timer_chkbx.setChecked(True)
        self.timer_chkbx.setObjectName("timer_chkbx")
        self.downl_fotorating_btn = QtWidgets.QPushButton(self.groupBox)
        self.downl_fotorating_btn.setGeometry(QtCore.QRect(150, 43, 151, 50))
        self.downl_fotorating_btn.setObjectName("downl_fotorating_btn")
        self.timer_label = QtWidgets.QLabel(self.groupBox)
        self.timer_label.setGeometry(QtCore.QRect(80, 130, 61, 20))
        self.timer_label.setObjectName("timer_label")
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMinimumSize(QtCore.QSize(310, 130))
        self.groupBox_3.setMaximumSize(QtCore.QSize(310, 160))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.login_edit_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.login_edit_line.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.login_edit_line.setMinimumSize(QtCore.QSize(150, 0))
        self.login_edit_line.setText("")
        self.login_edit_line.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.login_edit_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_edit_line.setReadOnly(False)
        self.login_edit_line.setClearButtonEnabled(True)
        self.login_edit_line.setObjectName("login_edit_line")
        self.password_edit_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.password_edit_line.setGeometry(QtCore.QRect(10, 40, 150, 20))
        self.password_edit_line.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_edit_line.setClearButtonEnabled(True)
        self.password_edit_line.setObjectName("password_edit_line")
        self.other_id_edit_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.other_id_edit_line.setGeometry(QtCore.QRect(10, 100, 150, 20))
        self.other_id_edit_line.setText("")
        self.other_id_edit_line.setDragEnabled(True)
        self.other_id_edit_line.setPlaceholderText("")
        self.other_id_edit_line.setClearButtonEnabled(True)
        self.other_id_edit_line.setObjectName("other_id_edit_line")
        self.login_label = QtWidgets.QLabel(self.groupBox_3)
        self.login_label.setGeometry(QtCore.QRect(170, 10, 111, 20))
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(self.groupBox_3)
        self.password_label.setGeometry(QtCore.QRect(170, 40, 121, 20))
        self.password_label.setObjectName("password_label")
        self.download_folder_edit_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.download_folder_edit_line.setGeometry(QtCore.QRect(10, 70, 150, 20))
        self.download_folder_edit_line.setInputMask("")
        self.download_folder_edit_line.setText("")
        self.download_folder_edit_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.download_folder_edit_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.download_folder_edit_line.setClearButtonEnabled(True)
        self.download_folder_edit_line.setObjectName("download_folder_edit_line")
        self.other_id_label = QtWidgets.QLabel(self.groupBox_3)
        self.other_id_label.setGeometry(QtCore.QRect(170, 100, 141, 20))
        self.other_id_label.setObjectName("other_id_label")
        self.downl_folder_label = QtWidgets.QLabel(self.groupBox_3)
        self.downl_folder_label.setGeometry(QtCore.QRect(170, 70, 100, 20))
        self.downl_folder_label.setObjectName("downl_folder_label")
        self.clear_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.clear_btn.setGeometry(QtCore.QRect(10, 130, 91, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_btn.sizePolicy().hasHeightForWidth())
        self.clear_btn.setSizePolicy(sizePolicy)
        self.clear_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.clear_btn.setObjectName("clear_btn")
        self.small_text_line = QtWidgets.QLabel(self.groupBox_3)
        self.small_text_line.setGeometry(QtCore.QRect(106, 130, 200, 25))
        self.small_text_line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.small_text_line.setObjectName("small_text_line")
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 160))
        self.groupBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.show_photo_chkbx = QtWidgets.QCheckBox(self.groupBox_2)
        self.show_photo_chkbx.setGeometry(QtCore.QRect(10, 130, 91, 20))
        self.show_photo_chkbx.setChecked(True)
        self.show_photo_chkbx.setObjectName("show_photo_chkbx")
        self.standard_radio_btn = QtWidgets.QRadioButton(self.groupBox_2)
        self.standard_radio_btn.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.standard_radio_btn.setChecked(True)
        self.standard_radio_btn.setObjectName("standard_radio_btn")
        self.base_radio_btn = QtWidgets.QRadioButton(self.groupBox_2)
        self.base_radio_btn.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.base_radio_btn.setChecked(False)
        self.base_radio_btn.setObjectName("base_radio_btn")
        self.help_radio_btn = QtWidgets.QRadioButton(self.groupBox_2)
        self.help_radio_btn.setGeometry(QtCore.QRect(10, 70, 82, 17))
        self.help_radio_btn.setObjectName("help_radio_btn")
        self.info_radio_btn = QtWidgets.QRadioButton(self.groupBox_2)
        self.info_radio_btn.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.info_radio_btn.setObjectName("info_radio_btn")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.main_text_window = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_text_window.sizePolicy().hasHeightForWidth())
        self.main_text_window.setSizePolicy(sizePolicy)
        self.main_text_window.setMinimumSize(QtCore.QSize(410, 300))
        self.main_text_window.setMaximumSize(QtCore.QSize(420, 3000))
        self.main_text_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_text_window.setReadOnly(True)
        self.main_text_window.setObjectName("main_text_window")
        self.gridLayout.addWidget(self.main_text_window, 1, 0, 1, 2)
        self.main_pic_window = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_pic_window.sizePolicy().hasHeightForWidth())
        self.main_pic_window.setSizePolicy(sizePolicy)
        self.main_pic_window.setMinimumSize(QtCore.QSize(300, 300))
        self.main_pic_window.setMaximumSize(QtCore.QSize(3000, 3000))
        self.main_pic_window.setAutoFillBackground(False)
        self.main_pic_window.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_pic_window.setLineWidth(0)
        self.main_pic_window.setText("")
        # self.main_pic_window.setPixmap(QtGui.QPixmap("pics for logo/Logo-4.jpg"))
        self.main_pic_window.setPixmap(QtGui.QPixmap(":/images/Logo32.jpg"))
        self.main_pic_window.setScaledContents(False)
        self.main_pic_window.setAlignment(QtCore.Qt.AlignCenter)
        self.main_pic_window.setObjectName("main_pic_window")
        self.gridLayout.addWidget(self.main_pic_window, 1, 2, 1, 2)
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.main_pic_window.raise_()
        self.groupBox.raise_()
        self.main_text_window.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "P_info_pic_saver"))
        self.downl_favor_btn.setToolTip(_translate("Form", "Скачать новые фото фаворитов"))
        self.downl_favor_btn.setText(_translate("Form", "Скачать Фаворитов"))
        self.download_enter_btn.setToolTip(_translate("Form", "Начать загрузку фото"))
        self.download_enter_btn.setText(_translate("Form", "Скачать (Enter)"))
        # self.download_enter_btn.setShortcut(_translate("Form", "Enter"))
        self.downl_best_btn.setToolTip(_translate("Form", "Скачать все фото Лучших пользователей"))
        self.downl_best_btn.setText(_translate("Form", "Скачать Лучших"))
        self.upate_base_btn.setToolTip(_translate("Form", "Запасная кнопка"))
        self.upate_base_btn.setText(_translate("Form", "Обновить Базу"))
        self.fotorate_folder_btn.setToolTip(_translate("Form", "Скачать все фото авторов из ПАПКИ фоторейтинга"))
        self.fotorate_folder_btn.setText(_translate("Form", "Фоторейтинг ПАПКА"))
        self.copy_folder_chkbx.setToolTip(_translate("Form", "Сделать копию скачанных фото в отдельной папке"))
        self.copy_folder_chkbx.setText(_translate("Form", "Копия"))
        self.timer_chkbx.setToolTip(_translate("Form", "Включить/выключить таймер закачки фоторейтинга"))
        self.timer_chkbx.setText(_translate("Form", "Таймер"))
        self.downl_fotorating_btn.setToolTip(_translate("Form", "Скачать все фото из фоторейтинга"))
        self.downl_fotorating_btn.setText(_translate("Form", "Скачать Фоторейтинг"))
        self.timer_label.setToolTip(_translate("Form", "Таймер"))
        self.timer_label.setText(_translate("Form", ""))
        self.login_label.setText(_translate("Form", "Ваш Логин на P.info"))
        self.password_label.setText(_translate("Form", "Ваш Пароль на P.info"))
        self.other_id_label.setText(_translate("Form", "ID другого пользователя"))
        self.downl_folder_label.setText(_translate("Form", "Папка загрузки"))
        self.clear_btn.setToolTip(_translate("Form", "Очистить область сообщений, уведомлений и область фото"))
        self.clear_btn.setText(_translate("Form", "Очистить"))
        self.small_text_line.setText(_translate("Form", ""))
        self.show_photo_chkbx.setToolTip(_translate("Form", "Показывать фото во время загрузки"))
        self.show_photo_chkbx.setText(_translate("Form", "Показ фото"))
        self.standard_radio_btn.setToolTip(_translate("Form", "Стандартный вывод"))
        self.standard_radio_btn.setText(_translate("Form", "Стандарт"))
        self.base_radio_btn.setToolTip(_translate("Form", "Показать базу пользователей"))
        self.base_radio_btn.setText(_translate("Form", "База"))
        self.help_radio_btn.setToolTip(_translate("Form", "Информация для желающих помочь проекту"))
        self.help_radio_btn.setText(_translate("Form", "Помощь"))
        self.info_radio_btn.setToolTip(_translate("Form", "Информация об авторе и программе"))
        self.info_radio_btn.setText(_translate("Form", "Инфо"))


